version: '3'
services:
  colux-db:
    image: mysql:8.0
    container_name: colux-db
    hostname: colux-db
    restart: always
    environment:
      MYSQL_DATABASE: 'COLUX_DB_CENTER'
      MYSQL_USER: 'colux'
      MYSQL_PASSWORD: 'coluxalpha2002'
      MYSQL_ROOT_PASSWORD: 'coluxalpha2002'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    networks:
      - colux-network
    volumes:
      - mysql-db:/var/lib/mysql
#
#  config-service:
#    image: coluxalpha/mmv3-spring-cloud-config-server:0.0.1-SNAPSHOT
#    container_name: config-server
#    hostname: config-server
#    restart: on-failure
#    ports:
#      - "8888:8888"
#    environment:
#      - SPRING_CONFIG_URI=http://spring-cloud-config-service:8888
#      - IDENTITY_SERVICE_URL=http://identity-service:8081
#    networks:
#      - colux-network
#
#  registry-service:
#    image: coluxalpha/mmv3-registry-services:0.0.1-SNAPSHOT
#    container_name: registry-service
#    restart: on-failure
#    ports:
#      - "8761:8761"
#    depends_on:
#      - config-service
#    environment:
#      - CONFIG_SERVER_URL=http://config-service:8888
#    networks:
#      - colux-network
#
#  apigateway:
#    image: coluxalpha/mmv3-api-gateway:0.0.1-SNAPSHOT
#    container_name: apigateway
#    hostname: apigateway
#    restart: on-failure
#    ports:
#      - "8765:8765"
#    expose:
#      - "8765"
#    depends_on:
#      - config-service
#    environment:
#      - SPRING_CONFIG_URI=http://spring-cloud-config-service:8888
#      - IDENTITY_SERVICE_URL=http://identity-service:8081
#    networks:
#      - colux-network
#
#
#  # =================== Services ===================
#
#  identity-service:
#    image: coluxalpha/mmv3-identity-service:0.0.1-SNAPSHOT
#    container_name: identity-service
#    hostname: identity-service
#    restart: on-failure
#    depends_on:
#      - config-service
#      - colux-db
#    ports:
#      - "8081:8081"
#    environment:
#      - CONFIG_SERVER_URL=http://config-service:8888
#    networks:
#      - colux-network

networks:
  colux-network:
    driver: bridge

volumes:
  mysql-db:
