services:
  colux-db:
    image: mysql:8.0
    container_name: colux-db
    hostname: colux-db
    restart: always
    environment:
      MYSQL_DATABASE: 'COLUX_DB_CENTER'
      MYSQL_USER: 'colux'
      MYSQL_PASSWORD: 'coluxalpha2002'
      MYSQL_ROOT_PASSWORD: 'coluxalpha2002'
    ports:
      - '3306:3306'
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - colux-network
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CREATE_TOPICS: "order-check-status:3:3"
      KAFKA_OFFSETS_RETENTION_MINUTES: 60
#  broker:
#    image: confluentinc/cp-kafka:7.5.0
#    container_name: broker
#    ports:
#      - "9092:9092"
#      - "29092:29092"
#    depends_on:
#      - zookeeper
#    environment:
#      KAFKA_BROKER_ID: 1
#      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
#      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
#      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
#      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
#
#  schema-registry:
#    image: confluentinc/cp-schema-registry:7.5.0
#    hostname: schema-registry
#    container_name: schema-registry
#    depends_on:
#      - broker
#    ports:
#      - "8085:8081"
#    environment:
#      SCHEMA_REGISTRY_HOST_NAME: schema-registry
#      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: 'broker:29092'
#      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081
#  kafka-ui:
#    container_name: kafka-ui
#    image: provectuslabs/kafka-ui:latest
#    ports:
#      - "8086:8080"
#    depends_on:
#      - broker
#    environment:
#      KAFKA_CLUSTERS_NAME: local
#      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
##      KAFKA_CLUSTERS_SCHEMAREGISTRY: http://schema-registry:8081
#      DYNAMIC_CONFIG_ENABLED: 'true'
#  config-service:
#    image: coluxalpha/mmv3-spring-cloud-config-server:0.0.1-SNAPSHOT
#    container_name: config-service
#    hostname: config-server
#    restart: on-failure
#    ports:
#      - "8888:8888"
#    expose:
#      - "8888"
#    networks:
#      - colux-network
#
#  apigateway:
#    image: coluxalpha/mmv3-api-gateway:0.0.3-SNAPSHOT
#    container_name: apigateway
#    hostname: apigateway
#    restart: on-failure
#    depends_on:
#      - identity-service
#      - config-service
#    environment:
#      - CONFIG_SERVER_URL=http://config-service:8888
#      - IDENTITY_SERVICE_URL=http://identity-service:8100
#      - SPRING_MAIN_WEB-APPLICATION-TYPE=reactive
#      - ROUTER_IDENTITY_SERVICE_URL=http://identity-service:8100
#      - ROUTER_PRODUCT_SERVICE_URL=http://product-service:8081
#      - ROUTER_ORDER_SERVICE_URL=http://order-service:8082
#      - API_GATEWAY_HOST=http://config-service:8888
#      - SPRING_CONFIG_URI=http://spring-cloud-config-service:8888
#      - IDENTITY_SERVICE_URL=http://identity-service:8081
#    networks:
#      - colux-network
#
# ============= Services ==================

#  identity-service:
#    image: coluxalpha/mmv3-identity-service:1.0.1-SNAPSHOT
#    container_name: identity-service
#    hostname: identity-service
#    restart: on-failure
#    depends_on:
#      - colux-db
#      - config-service
#    ports:
#      - "8100:8100"
#    expose:
#      - "8100"
#    environment:
#      - API_GATEWAY_HOST=apigateway
#      - CONFIG_SERVER_URL=http://config-service:8888
#      - SPRING_PROFILES_ACTIVE=dev
#      - MYSQL_HOST=colux-db
#    networks:
#      - colux-network
#    command: sh -c "sleep 20 && java -jar your-app.jar"
#
#  product-service:
#    image: coluxalpha/mmv3-product-service:0.0.12-SNAPSHOT
#    container_name: product-service
#    hostname: product-service
#    restart: on-failure
#    depends_on:
#      - colux-db
#      - config-service
#    ports:
#      - "8081:8081"
#    environment:
#      - CONFIG_SERVER_URL=http://config-service:8888
#      - MYSQL_HOST=colux-db
#      - SPRING_PROFILES_ACTIVE=dev
#    networks:
#      - colux-network
#    command: sh -c "sleep 20 && java -jar your-app.jar"


networks:
  colux-network:
    driver: bridge

volumes:
  mysql_data:
