app:
  api-prefix: /api/v1
spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  profiles:
    active: ${ACTIVE_PROFILE:dev}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=${app.api-prefix}/user/**
          filters:
            - name: RewritePath
              args:
                regexp: /user/(?<segment>.*)
                replacement: /$\{segment}
        - id: currency-exchange-service
          uri: lb://currency-exchange
          predicates:
            - Path=/currency-exchange/**
          filters:
            - name: RewritePath
              args:
                regexp: /currency-exchange/(?<segment>.*)
                replacement: /$\{segment}
server:
  port: ${CONTAINER_PORT:8080}
  error:
    path: /user/error
    whitelabel:
      enabled: false

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}
