spring:
  data:
    mongodb:
      uri: mongodb://localhost:27017/customer-service
      username: colux
      password: dreamaker789
      host: localhost
      port: 27017
      database: customer
      authentication-database: admin

server:
  port: 8082