app:
  api-prefix: /api/v1
spring:
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false
      close-closeable: true
      flush-after-write-value: true
      write-date-keys-as-timestamps: false
    deserialization:
      fail-on-unknown-properties: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATA_BASE_NAME}?useSSL=false
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
      format_sql: true
      use_sql_comments: true
      jdbc:
        time_zone: UTC
  sql:
    init:
      mode: never
      continue-on-error: false
      data-locations: classpath:data/data.sql
      schema-locations: classpath:data/schema.sql
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB
  mail:
    host: ${EMAIL_HOST}
    port: ${EMAIL_PORT}
    username: ${EMAIL_ID}
    password: ${EMAIL_PASSWORD}
    properties:
      mail:
        mime:
          charset: UTF-8
        smtp:
          write:
            timeout: 10000
          connection:
            timeout: 10000
          auth: true
          starttls:
            enable: true
            required: true
    verify:
      host-server: ${VERIFY_EMAIL_HOST}

server:
  port: ${CONTAINER_PORT:8080}
  error:
    path: /user/error
    whitelabel:
      enabled: false

jwt:
  expiration: ${JWT_EXPIRATION}
  secret: ${JWT_SECRET}