# Configuration identity service for dev environment
MYSQL_HOST: localhost
MYSQL_PORT: 3306
DATA_BASE_NAME: PRODUCTSERVICE_DB
MYSQL_USER: root
MYSQL_PASSWORD: admin


ACTIVE_PROFILE: dev
CONTAINER_PORT: 8081

#Email configuration
EMAIL_HOST: smtp.gmail.com
EMAIL_PORT: 587
EMAIL_ID: hoduy8701@gmail.com
EMAIL_PASSWORD: cupaigjgehoemtpd
VERIFY_EMAIL_HOST: http://localhost:8765

#JWT configuration
JWT_EXPIRATION: 432_000_000
#JWT_SECRET: ${"SECRET_KEY"}
JWT_SECRET: lasflaksjflkjqowierkjashdfkjahsdkfjhaslfiwuqyoqiuwhlaksvbjxcmvnbqpweuqpweiufqywoeiurhjsadgbflajseujnasdfaosifjjnkahskdhfalsf

spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${DATA_BASE_NAME}?useSSL=false&allowPublicKeyRetrieval=true
