spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/DuyHD75/Colux_BE_Config_Server.git
          username: DuyHD75
          password: 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

server:
  port: 8888