spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/DuyHD75/Colux_BE_Config_Server.git
          username: DuyHD75
          password: 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

server:
  port: 8888